### ISSUE TITLE
[FEATURE] Authentication

### ISSUE THREAD

**Issue by thatguycodes** [BuildForSDG/team-275#15]
ETC: 22-May-2020
- [x] reactive form to extract login payload
- [x]  reactive form to extract registration payload
- [ ] validations to ensure compliance to models
- [ ] create model in the frontend
- [ ] create model in the backend
- [ ] service to integrate with backend http transaction
- [ ] messages to indicate status of the http transaction on the frontend views
- [ ] send email with activation token
- [ ] send email for successful change of password
- [ ] create http interceptors
- [ ] create unit test for each of the above
- [ ] landing page

**Comment by wiredmartian** [comment]
Resolved on PR #17
